### ISSUE TITLE
Class not found error when using prefix option

### ISSUE THREAD

**Issue by chadevans1** [NISystemsEngineering/CEF#84]
IF I use the "File Name Prefix (optional)" option on the "Configuration Editor Project" template, then I get the "class cannot be found" error.

**Comment by becega** [comment]
This is a repeated issue with "[Project not linking libraries if suffix is changed. #78](Project not linking libaries if suffix is changed)".  The editor still loads the class, but the class when you change the prefix, no longer matches the class called by the editor nodes. In order to modify the prefix you would need to modify all the VIs that have the current class names. In the newest version we just removed this option.
